### ISSUE TITLE
item_group error

### ISSUE THREAD

**Issue by Gogol83** [biasinrecsys/umap2020#1]
Hi,

I am getting the following error while executing the block in notebook 1:

#Code block

item_group = load_obj(os.path.join(data_path, 'datasets', 'ml1m-item-group')) 

# Error

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-40-7168aa4c3fa4> in <module>()
----> 1 item_group = load_obj(os.path.join(data_path, 'datasets', 'ml1m-item-group'))
      2 # we discuss this point in detail in the third notebook

/content/gdrive/My Drive/umap2020/helpers/utils.py in load_obj(name)
     11 
     12 def load_obj(name):
---> 13     with open(name, 'rb') as f:
     14         return pickle.load(f)
     15 

FileNotFoundError: [Errno 2] No such file or directory: '../data/datasets/ml1m-item-group'

Could you please help? Should there be another file in the datasets folder?

**Comment by biasinrecsys** [comment]
Dear Gogol83,

The missing file has been pushed into the repository. Once you pull it, you should be able to run the notebooks.
We would like also to invite you to visit the repositories of the more recent tutorials. 

Best,
